### ISSUE TITLE
alumni section

### ISSUE THREAD

**Issue by whoburg** [aeroa/aeroa.github.io#16]
Let's have an alumni section on the people page

**Comment by 1ozturkbe** [comment]
Quick to make. Has been pushed to master. Closing.

**Comment by whoburg** [comment]
Awesome! Thanks @1ozturkbe.

How should we add current employment/status?

**Comment by 1ozturkbe** [comment]
One (simple) way would be through a clickable bio, since we already have the infrastructure for that. But it might perhaps be better to put the current status in the people page, and explain the alumnus' degree and research contributions in the biolink. Or we could do what you had initially suggested, and put all the bios in the people page, although that might be cluttered and difficult to implement because of people who have external links for bios (i.e. you :) ). I don't have any strong feelings about it, so whatever you think is best. 

Also, I definitely should have included graduation date for every alumnus (well, just Phillippe!). Will fix during my next pass.

**Comment by whoburg** [comment]
I'll write a bio for the website -- it need not be separate!
